version: 2
updates:
  - package-ecosystem: 'github-actions'
    target-branch: 'main'
    directory: '/'
    schedule:
      day: 'monday'
      time: '08:00'
      interval: 'weekly'
      timezone: 'Europe/London'
    reviewers:
      - 'amaziein'
    assignees:
      - 'amaziein'
    labels: []
