export const countriesMap = new Map([
  ['austria', '/countries/austria.svg'],
  ['belgium', '/countries/belgium.svg'],
  ['croatia', '/countries/croatia.svg'],
  ['cyprus', '/countries/cyprus.svg'],
  ['czech republic', '/countries/czech-republic.svg'],
  ['denmark', '/countries/denmark.svg'],
  ['estonia', '/countries/estonia.svg'],
  ['finland', '/countries/finland.svg'],
  ['france', '/countries/france.svg'],
  ['germany', '/countries/germany.svg'],
  ['greece', '/countries/greece.svg'],
  ['hungary', '/countries/hungary.svg'],
  ['iceland', '/countries/iceland.svg'],
  ['ireland', '/countries/ireland.svg'],
  ['italy', '/countries/italy.svg'],
  ['latvia', '/countries/latvia.svg'],
  ['liechtenstein', '/countries/liechtenstein.svg'],
  ['lithuania', '/countries/lithuania.svg'],
  ['luxembourg', '/countries/luxembourg.svg'],
  ['malta', '/countries/malta.svg'],
  ['monaco', '/countries/monaco.svg'],
  ['netherlands', '/countries/netherlands.svg'],
  ['norway', '/countries/norway.svg'],
  ['poland', '/countries/poland.svg'],
  ['portugal', '/countries/portugal.svg'],
  ['romania', '/countries/romania.svg'],
  ['san marino', '/countries/san-marino.svg'],
  ['slovakia', '/countries/slovakia.svg'],
  ['slovenia', '/countries/slovenia.svg'],
  ['spain', '/countries/spain.svg'],
  ['sweden', '/countries/sweden.svg'],
  ['switzerland', '/countries/switzerland.svg'],
  ['united kingdom', '/countries/united-kingdom.svg'],
]);
