name: Node.js CI

on: [pull_request]

env:
  MYGET_NPM_TOKEN: ${{ secrets.READ_MYGET_NPM_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
          
      - name: Install node modules
        run: npm i
          
      - name: Run all unit tests
        run: npm run test
