name: Node.js CI

on: [pull_request]

env:
  MYGET_NPM_TOKEN: ${{ secrets.READ_MYGET_NPM_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
          
      - name: Install node modules
        run: npm i --ignore-scripts
          
      - name: Run all unit tests
        run: npm run test
        
      - name: Lint
        run: npm run lint
        
      - name: Type check
        run: npm run type-check
        
      - name: Build
        run: npm run build
